#
# Copyright (C) 2008-2012 Matthew Turner. Distributed under the GPL v3.
#
# Directory makefile fragment.
#

CONFIG_HERE := $(SRC_ROOT)/config

vpath %.c $(CONFIG_HERE)
vpath %.xsl $(CONFIG_HERE)
vpath %.xml $(CONFIG_HERE)

config_%.h: config_%_h.xsl config-config.xml
	xsltproc $^ > $@
config_%.c: config_%_c.xsl config-config.xml
	xsltproc $^ > $@

# Should list these explicitly, really
CONFIG_SOURCES = $(wildcard $(CONFIG_HERE)/*.c)
CONFIG_OBJECTS = $(patsubst %.c,%.o,$(notdir $(CONFIG_SOURCES)))

# Autogenerated files
CONFIG_AUTO_SOURCES = config_declare.h \
                      config_defaults.c \
                      config_xml_info.c \
                      config_reader_functions.h \
                      config_reader_functions.c
CONFIG_AUTO_OBJECTS = $(patsubst %.c,%.o,$(filter %.c,$(CONFIG_AUTO_SOURCES)))

OBJECTS += $(CONFIG_OBJECTS) $(CONFIG_AUTO_OBJECTS)
AUTO_SOURCES += $(CONFIG_AUTO_SOURCES)
